[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/clientes/*"
  to = "/.netlify/functions/clientes/:splat"
  status = 200

[[redirects]]
  from = "/api/clientes"
  to = "/.netlify/functions/clientes"
  status = 200
